export interface PatternImage {
  filename: string;
  type: "product_photo" | "crochet_diagram" | "text_diagram" | "symbol_diagram" | "other" | "unclassified";
  thumb: string;
  medium: string;
  full: string;
}

export interface PatternTranslation {
  englishText: string;
  chineseText: string;
  notes: string;
}

export interface PatternFaq {
  question: string;
  answer: string;
}

/**
 * Structured enrichment fields, generated by the LLM export pipeline from the
 * pattern text/notes and spot-checked by a human. All optional: patterns without
 * them render and rank fine, they just miss the richer info block / schema.
 */
export interface PatternMeta {
  /**
   * Optional SEO override for the SERP <title> (and OG/Twitter title). When set,
   * it replaces the default `${title} Crochet Pattern`. Keep it ≤ ~50 chars — the
   * site template appends " | Hooklore". Used to differentiate near-duplicate
   * pages (e.g. multiple Earth-globe patterns) and lift click-through. Does NOT
   * affect the on-page H1 or the URL slug.
   */
  seoTitle?: string;
  /** 1–2 sentence English summary — feeds meta description + schema + AI answers. */
  intro?: string;
  materials?: string[];
  yarnWeight?: string;
  hookSize?: string;
  finishedSize?: string;
  difficulty?: "Beginner" | "Easy" | "Intermediate" | "Advanced" | string;
  estimatedTime?: string;
  /** Crochet abbreviations actually used in this pattern (e.g. ["sc", "inc"]). */
  abbreviationsUsed?: string[];
  faq?: PatternFaq[];
}

export interface Pattern {
  id: number;
  slug: string;
  title: string;
  description: string;
  author: string;
  tags: string[];
  createdAt: string;
  /** Last content edit (translation/enrichment). Falls back to createdAt when absent. */
  updatedAt?: string;
  productPhotos: PatternImage[];
  diagrams: PatternImage[];
  allImages: PatternImage[];
  patterns: PatternTranslation[];
  /** Optional structured enrichment (see PatternMeta). */
  meta?: PatternMeta;
}

export interface TagInfo {
  slug: string;
  label: string;
  count: number;
}
