/**
 * Hand-written intro copy for tag landing pages. Only tags that meet the
 * indexability threshold (see MIN_INDEXABLE_TAG_COUNT) need an entry — pages
 * without one fall back to a generic paragraph. Keep each intro unique and
 * roughly 100–150 words so the page reads as a real landing page rather than
 * a bare image grid. Paragraph breaks: "\n\n".
 */
export const TAG_INTROS: Record<string, string> = {
  amigurumi: `Amigurumi is the Japanese art of crocheting small stuffed creatures, and it remains the fastest way to turn a ball of yarn into a gift someone actually squeals over. This collection gathers free amigurumi crochet patterns for animals, characters and food-shaped plushies, each translated into US-standard notation with round-by-round stitch counts, so you always know how many stitches you should have before moving on.\n\nMost designs here are worked in continuous spirals of single crochet with basic increases and invisible decreases — beginner-friendly territory once you can crochet a magic ring. Grab a hook one or two sizes smaller than your yarn suggests so the stuffing never shows through, and start with a smaller piece before committing to a large plush.`,

  accessory: `Crocheted accessories are the sweet spot between quick wins and everyday use: hair clips, brooches, keychains, bag charms, cup sleeves and other small pieces you can finish in an evening and actually wear the next day. This page collects free accessory crochet patterns with clear US-notation instructions, photos of the finished piece, and stitch-by-stitch counts.\n\nBecause most accessories use only scraps of yarn, they are ideal for testing new colour combinations or using up leftovers from bigger projects. Many of these designs come from talented Chinese crochet artists whose charts we have translated into English — the aesthetic leans cute, detailed and a little unexpected, which makes these pieces great small gifts and market-stall sellers.`,

  animal: `Animal crochet patterns are perennial favourites for a reason: whether it is a tiny sparrow, a plump elephant or a curled-up cat, an animal shape reads instantly and forgives small imperfections. Here you will find free animal crochet patterns — mostly amigurumi plushies, plus some appliqués and motifs — each with translated, US-standard instructions and per-round stitch counts.\n\nIf you are new to crocheting animals, start with a design that uses one colour and simple limbs before graduating to colourwork or wire-framed poses. Safety eyes give the cleanest look, but embroidered eyes are the safer choice for anything destined for a baby or a pet-adjacent household.`,

  character: `Character crochet patterns let you recreate the faces you already love — game characters, cartoon icons and original mascot-style designs — as plushies, charts and appliqués. This collection of free character crochet patterns is translated from original Chinese charts into US-standard notation, with photos and stitch counts to keep you on track.\n\nCharacter work rewards precision: the difference between "adorable" and "cursed" is usually eye placement, so pin features before sewing and check the reference photos often. Expect colour changes and a bit of embroidery on most of these designs; if you are new to colourwork, pick a character with large blocks of colour before attempting fine details.`,

  bag: `A crocheted bag is one of the most satisfying larger projects: unlike garments there is no sizing anxiety, and the fabric's structure matters more than gauge perfection. This page gathers free crochet bag patterns — net bags, granny-square totes, mini pouches, earphone cases and shoulder bags — with translated US-notation instructions and stitch counts.\n\nFor bags that need to carry real weight, choose cotton or a cotton blend over acrylic, and work tighter than you would for a plushie so the fabric does not sag. Many of the designs here are quick single-skein projects; the larger totes take a weekend or two. Lining is optional but transforms a handmade bag into something that reads store-bought.`,

  lace: `Lace crochet is where the craft shows off: doilies, lace collars, openwork motifs and delicate edgings built from chains, picots and shell clusters. This collection of free lace crochet patterns pairs charted designs from Chinese crochet artists with translated, US-standard written instructions so you can follow whichever format you prefer.\n\nLace rewards patience over speed — count your chains, use stitch markers on long foundation rows, and always block your finished piece; wet blocking is the step that turns a crumpled cluster of stitches into crisp, symmetrical lace. Mercerised cotton thread gives the classic look, but many of these patterns also work beautifully in fingering-weight yarn for a softer, larger result.`,

  flower: `Crocheted flowers never wilt, and they are the perfect scrap-yarn project: most take under thirty minutes and a few metres of yarn. Here you will find free crochet flower patterns — roses, daisies, layered blossoms, flower appliqués and granny squares with floral centres — each translated into US-standard notation with clear round-by-round counts.\n\nFlowers are also the best way to practise new stitches in miniature: picots, clusters, and standing stitches all show up in petal work. Stiffen finished flowers with a fabric stiffener spray if they will decorate bags or hair clips, and layer two or three sizes of the same flower for instant depth. They make lovely embellishments for hats, blankets and gift wrapping.`,

  home: `Crochet for the home is where handmade earns its keep: coasters, placemats, baskets, wall hangings and decorative pieces you see and use every day. This page collects free home decor crochet patterns with translated US-notation instructions, finished-object photos and stitch counts.\n\nHome items are more forgiving than garments — nobody tries on a coaster — which makes them ideal first projects beyond scarves. Cotton yarn is the default choice here: it holds shape, survives washing and handles hot mugs without melting, all things acrylic struggles with. Start with a flat circular piece to master increasing in the round, then work up to baskets and textured pieces.`,

  wearable: `Wearable crochet covers everything you put on your body: scarves, collars, hats, shawls and small garment pieces. This collection of free wearable crochet patterns focuses on accessible, well-photographed designs translated into US-standard notation — pieces you can realistically finish and actually wear, rather than sweater-sized commitments.\n\nWith wearables, drape is everything: check the pattern's suggested yarn weight and swatch if you substitute, because a fabric that is perfect for a plushie will feel like cardboard around your neck. Natural fibres and blends breathe better than pure acrylic for anything worn against skin. Scarves and collars here are great entry points before attempting fitted garments.`,

  gaming: `Gaming crochet patterns turn pixels into yarn — plushies and pixel charts inspired by the games you have sunk hundreds of hours into. This page gathers free game-themed crochet patterns, from character amigurumi to full pixel-art charts, each translated into US-standard instructions with stitch counts and colour guides.\n\nPixel-based designs are essentially colourwork grids: if you can count squares, you can crochet them, using tapestry crochet, corner-to-corner or plain single crochet rows. Character plushies are more sculptural and suit crocheters comfortable with amigurumi basics. Either way these make legendary gifts for the gamer in your life — few things say "I know you" like their favourite character in yarn form.`,

  food: `Food amigurumi is pure serotonin: tiny crocheted fruit, vegetables, desserts and snacks that double as play food, keychains and desk companions. Here you will find free food crochet patterns with translated US-standard instructions and round-by-round stitch counts, mostly quick single-evening makes.\n\nFood shapes are the friendliest introduction to amigurumi — a strawberry is just a cone, an orange is just a sphere — so this is a great tag to browse if you are new to stuffed crochet. Colour choice does most of the work: use saturated, true-to-life colours and firm stuffing so a peach looks ripe rather than deflated. Crocheted play food also survives toddler enthusiasm far better than plastic.`,

  coaster: `Coasters are the gateway drug of crochet-for-the-home: flat, fast, useful and endlessly variable. This page collects free crochet coaster patterns — scalloped rounds, lace-edged circles, animal faces and pixel designs — each translated into US-standard notation with per-round stitch counts.\n\nA coaster is really a lesson in working flat circles: master the increase rhythm here and you have the foundation for hats, baskets and rugs. Use cotton yarn (it tolerates heat and washing), keep tension snug so the coaster lies flat, and block the finished piece between two books overnight. If your circle ruffles you increased too much; if it cups, too little — the fix is one round away either way. A matching set makes an excellent housewarming gift.`,

  toy: `Crocheted toys are built to be loved hard: plushies, rattles and play pieces that survive being dragged, chewed and slept on. This collection of free toy crochet patterns comes with translated US-standard instructions, stitch counts and assembly photos.\n\nToy crochet has two golden rules. First, safety: for anything given to children under three, embroider the eyes instead of using plastic safety eyes, and stitch limbs on firmly. Second, durability: work tightly with a smaller hook than the yarn band suggests, stuff firmly, and choose machine-washable yarn because the toy will end up somewhere unspeakable. Beyond that, relax — small irregularities disappear entirely once a child adopts the thing.`,

  decor: `Decorative crochet pieces — wall hangings, ornaments, standing figures and display items — let you crochet purely for the joy of the object. This page gathers free decor crochet patterns translated into US-standard notation, with photos and stitch-by-stitch counts.\n\nUnlike toys and wearables, decor pieces never need to survive washing or wear, which frees you to use metallic threads, wire framing, stiffeners and delicate yarns that would be impractical elsewhere. Blocking and finishing matter more than usual, though: a display piece is looked at, not hugged, so take the extra evening to weave ends invisibly and shape it properly. These are also lovely seasonal makes — ornaments and small hangings work up quickly in gift-giving months.`,

  "doll-clothes": `Doll clothes are miniature dressmaking with none of the fabric waste: tiny sweaters, dresses, hats and outfits for BJDs, Blythes, plush dolls and their kin. This collection of free doll clothes crochet patterns is translated into US-standard notation with stitch counts and fitting photos.\n\nWorking at doll scale means thin yarn and small hooks — typically lace or fingering weight on a 1.5–2.5 mm hook — so every stitch shows, and tension consistency matters more than speed. The payoff is that an entire garment takes hours, not weeks, making doll clothes the perfect way to learn garment construction: raglan shaping, buttonbands and skirt gathers all work identically at full size. Check your doll's measurements against the pattern before starting; doll bodies vary wildly between brands.`,

  applique: `Crochet appliqués are small flat motifs — animals, flowers, hearts, letters — made to be sewn onto something else: bags, beanies, blankets, jackets. This page collects free crochet applique patterns with translated US-standard instructions and per-round stitch counts.\n\nAppliqués are the quickest projects on this site; most take under an hour and a few grams of yarn, which makes them perfect for testing colours and using up scraps. Work them slightly tighter than usual so the edges stay crisp, block flat before attaching, and sew with a sharp needle through the back loops only so the stitching disappears. A plain store-bought beanie plus one well-placed appliqué equals a handmade-looking gift in an evening.`,

  motif: `Motifs are crochet's building blocks: squares, circles, hexagons and shaped units designed to be joined into blankets, bags, garments — or used alone as coasters and appliqués. Here you will find free crochet motif patterns translated into US-standard notation, each with charted logic explained round by round.\n\nThe beauty of motif work is portability and modularity: each unit is a complete, pocket-sized project, and the join-as-you-go technique turns a pile of them into fabric without a marathon sewing session. Pay attention to blocking — motifs joined at different tensions will fight each other forever — and make one complete test unit before cutting yarn for forty. A single motif repeated in good colours beats a complicated one in muddy ones every time.`,

  doll: `Crocheted dolls sit at the ambitious end of amigurumi: figures with faces, hair, clothes and personality, from small pocket dolls to detailed display pieces. This collection of free doll crochet patterns includes translated US-standard instructions, stitch counts and assembly guidance.\n\nDolls demand more finishing skill than animals — face embroidery, hair attachment and garment details are where a doll comes alive, and where it pays to go slowly. Pin everything before sewing, embroider features with a single strand for fine control, and accept that the first face attempt usually gets redone. If you are new to dolls, start with one whose hair is a crocheted cap rather than individually attached strands; your patience will thank you.`,

  "pixel-chart": `Pixel charts translate grid-based artwork directly into crochet: each square on the chart is one stitch, worked in single crochet, tapestry crochet or corner-to-corner. This page gathers free crochet pixel chart patterns — characters, animals and seasonal designs — with colour keys and grid counts, translated from the original Chinese charts.\n\nPixel work is less about technique and more about bookkeeping: use a row counter, tick off chart rows as you go, and manage yarn bobbins for each colour block to avoid a tangled nightmare on the wrong side. The charts here range from small motifs to full blanket-scale artwork like a 138-stitch-wide angel. If you can follow a spreadsheet, you can crochet these.`,

  "stardew-valley": `Stardew Valley and yarn crafts are a natural pairing — half the game is farming cozy vibes anyway. This page collects free Stardew Valley–inspired crochet patterns: character pixel charts and motifs of villagers and icons from the valley, translated into US-standard notation with colour keys and grid counts.\n\nMost designs here are pixel-art charts, which work up faithfully because the game's own sprites are pixel art — what you see on screen is almost exactly what you crochet. Work them as tapestry crochet for a dense, game-accurate fabric, or single crochet rows with bobbins for larger pieces. These make devastatingly effective gifts for anyone who has ever apologised out loud to Sebastian.`,

  bird: `Birds are a joy to crochet: compact bodies, expressive shapes, and endless colour possibilities from realistic sparrows to stylised round chicks. This collection of free bird crochet patterns includes amigurumi plushies and motifs, each translated into US-standard notation with round-by-round stitch counts.\n\nBird amigurumi is mostly sphere-and-cone construction, which makes it approachable, but the character lives in the details: beak placement, eye height and the angle of the head decide whether your bird looks alert, sleepy or unhinged — pin before you sew. Wire in the legs is optional but lets a finished bird actually perch. Small birds use so little yarn that a whole flock costs one skein.`,

  "micro-crochet": `Micro crochet is regular crochet at doll-house scale: embroidery thread or fine lace yarn worked on hooks between 0.5 and 1.0 mm, producing finished pieces measured in centimetres. This page collects free micro crochet patterns translated into US-standard notation — tiny animals, miniature accessories and jewellery-scale motifs.\n\nThe patterns themselves are usually simple; the challenge is entirely physical. Work in strong daylight, take breaks before your hands cramp, and use a hook with a comfortable handle because pencil-thin steel hooks are brutal over long sessions. Thread crochet shows every stitch, so consistent tension matters more than speed. The payoff: pieces delicate enough to wear as earrings or perch on a fingertip, from a single evening and pennies of thread.`,

  cat: `Cats are the internet's favourite animal and crochet's too: this page gathers free cat crochet patterns, from amigurumi kittens to cat-face motifs, scarves and pixel-art placemats, each translated into US-standard notation with stitch counts.\n\nCat designs live or die on the face: whisker placement, eye shape and ear angle carry all the personality, so embroider features before assembling and check them against the reference photos from multiple angles. For black cats — a running favourite here — use a slightly larger hook or lighter-coloured stitch markers, because counting black stitches at night is its own circle of hell. These patterns range from single-evening motifs to weekend plushie projects.`,

  hair: `Crocheted hair accessories are tiny, fast and endlessly giftable: scrunchies, hair clips, bows and flower pins that take an evening and a handful of yarn. This collection of free hair accessory crochet patterns comes with translated US-standard instructions and stitch-by-stitch counts.\n\nThe trick with hair pieces is structure: work tightly, and stiffen flat pieces like bows and flowers so they hold shape against daily wear. Sew finished motifs onto blank clips or French barrettes from any craft store — the hardware costs pennies and instantly makes the piece wearable. Cotton and mercerised threads give the crispest results; fuzzy yarns read messy at this scale. These are ideal market-stall items and party favours.`,

  "granny-square": `The granny square is crochet's most iconic motif: clusters of double crochet worked in rounds from the centre out, infinitely customisable and famously portable. This page collects free granny square crochet patterns — classic squares, floral-centre variations and four-corner units — with translated US-standard instructions and charted logic explained round by round.\n\nIf you are new to granny squares, master the classic square first: it teaches corner spacing and cluster rhythm that every variation builds on. Change colours between rounds to use up scraps, and block your squares before joining or the finished blanket will never lie flat. One square is an afternoon; a blanket is a winter — both are worth it.`,

  fruit: `Crocheted fruit is amigurumi at its most cheerful: strawberries, oranges, peaches and friends, worked up in an evening and impossible to look at without smiling. This page gathers free fruit crochet patterns with translated US-standard instructions and round-by-round stitch counts.\n\nFruit is the ideal first amigurumi because the shapes are basic geometry — spheres, cones and teardrops — with no limbs to attach or faces to place. Colour does the heavy lifting: pick saturated, true-to-life shades and stuff firmly so the fruit looks ripe. Add a keychain ring and they become bag charms; make a basketful and they become play food that outlasts any plastic set.`,

  scarf: `A scarf is the classic first crochet project, but the designs here go beyond the basic rectangle: cat-face motif scarves, flower-and-bird designs and other character pieces translated into US-standard notation with stitch counts and assembly photos.\n\nScarves teach the most transferable skill in crochet — maintaining even tension over long rows — and forgive experimentation more than any garment. For anything worn against the neck, yarn choice outranks pattern choice: a soft acrylic, cotton blend or superwash wool beats a scratchy bargain skein no matter how pretty the stitchwork. Motif-based scarves like the ones here are also more portable than blanket projects: each unit is a small win you can finish on a commute.`,
};
